# Generated by Django 4.2.13 on 2024-05-26 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_whatyoulearn_requirements'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Requirements',
            new_name='Requirement',
        ),
    ]
