# Generated by Django 4.2.13 on 2024-05-26 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_requirements_requirement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requirement',
            old_name='points',
            new_name='point',
        ),
        migrations.RenameField(
            model_name='whatyoulearn',
            old_name='points',
            new_name='point',
        ),
    ]
